# Generated by Django 5.2.5 on 2026-05-07 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_communitypost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('group_type', models.CharField(choices=[('open', 'Open Group'), ('moderated', 'Moderated'), ('age_specific', 'Age-Specific')], default='open', max_length=15)),
                ('format_type', models.CharField(choices=[('online', 'Online'), ('hybrid', 'Hybrid'), ('in_person', 'In-Person')], default='online', max_length=10)),
                ('schedule_day', models.CharField(blank=True, max_length=30)),
                ('schedule_time', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='support_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
