# Generated by Django 5.2.5 on 2026-05-07 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_signs_personal', models.TextField(blank=True)),
                ('warning_signs_observable', models.TextField(blank=True)),
                ('coping_strategies', models.TextField(blank=True)),
                ('coping_effectiveness', models.JSONField(blank=True, default=list)),
                ('support_contacts', models.JSONField(blank=True, default=list)),
                ('professional_contacts', models.JSONField(blank=True, default=list)),
                ('environment_safety', models.TextField(blank=True)),
                ('reasons_for_living', models.TextField(blank=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
